version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: List Directory Contents
          command: ls -la
      - run:
          name: Install Backend Dependencies
          command: |
            if [ -d "BACKEND" ]; then
              cd BACKEND
              npm install
            else
              echo "Backend directory not found"
              exit 1
            fi
      - run:
          name: Run Backend Tests
          command: |
            if [ -d "BACKEND" ]; then
              cd BACKEND
              npm test
            else
              echo "Backend directory not found"
              exit 1
            fi
      - persist_to_workspace:
          root: .
          paths:
            - BACKEND

  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run SonarQube Scan
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-main}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            echo "Sonar org value is: $SONAR_ORGANIZATION"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORGANIZATION" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.token="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="BACKEND" \
              -Dsonar.exclusions="BACKEND/node_modules/**" \
              -Dsonar.c.file.suffixes=- \
              -Dsonar.cpp.file.suffixes=- \
              -Dsonar.objc.file.suffixes=-

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - sonarqube:
          requires:
            - build